#!/usr/bin/env bash

base_dir="$( cd "$( dirname "$0" )" && pwd )"
source "$base_dir/global"

uninstall_code_server() {
    rm -rf $code_server_target_service_file
    sudo systemctl stop code-server
    rm /usr/bin/code-server
    rm -rf /usr/lib/code-server
}

delete_code_server_installer_including_downloaded_tarball() {
    rm -rf /tmp/code-server/
}


delete_nginx() {
    rm -f /etc/nginx/sites-enabled/code-server.conf
    rm -f /etc/nginx/sites-available/code-server.conf
    sudo systemctl stop nginx
    sudo apt-get remove certbot -y
    sudo apt-get remove python3-certbot-nginx -y
    sudo apt-get remove nginx -y
    sudo apt-get autoremove -y
}

uninstall_code_server
delete_code_server_installer_including_downloaded_tarball
delete_nginx
